version: '3.1'

services:
  jupyter:
    build: './jupyter'
    restart: always
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
  # api:
  #   build: '.'
  #   ports:
  #     - 3000:3000
  #   logging:
  #     driver: 'json-file'
  #     options:
  #       max-file: '5'
  #       max-size: '50m'
  #   environment:
  #     NODE_ENV: 'production'
  mongo:
    image: mongo:5.0.5
    restart: always
    hostname: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://username:password@mongo:27017/"
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: appademin
      ME_CONFIG_BASICAUTH_PASSWORD: kaffesmakpådongeln
