version: '3.1'

services:
  caddy:
    build: './caddy'
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - adminer
    volumes:
      - /data/caddy:/root/.caddy
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '50m'
  api:
    build: './api'
    depends_on:
      - postgres
    ports:
      - 3000:3000
    links:
      - python-api
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '50m'
    environment:
      NODE_ENV: 'production'
      DB_HOST: postgres
      DB_PORT: 5432
      PYTHON_API: http://python-api
      DB_USERNAME: admin
      DB_PASSWORD: password
      DB: sci
  python-api:
    build: './api/python'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  postgres:
    image: postgres:14.1
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - /data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sci
      PGDATA: /var/lib/postgresql/data/pgdata
