version: '3.1'

services:
  caddy:
    build: './caddy'
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - jupyter
      - mongo-express
    volumes:
      - /data/caddy:/root/.caddy
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '50m'
  jupyter:
    build: './jupyter'
    restart: always
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
  api:
    build: '.'
    depends_on:
      - mongo
    ports:
      - 3000:3000
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '50m'
    environment:
      NODE_ENV: 'production'
      MONGO_URL: mongodb://username:password@mongo:27017
      MONGO_DB: sci
  mongo:
    image: mongo:5.0.5
    restart: always
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://username:password@mongo:27017/'
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: appademin
      ME_CONFIG_BASICAUTH_PASSWORD: kaffesmakpådongeln
  postgres:
    image: postgres:14.1
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sci
      PGDATA: /var/lib/postgresql/data/pgdata
