version: '3.1'
services:
  jupyter:
    build: './jupyter'
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
  # api:
  #   build: './api'
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 4000:4000
  #   environment:
  #     NODE_ENV: 'production'
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: admin
  #     DB_PASSWORD: password
  #     DB: sci
  postgres:
    image: postgres:14.1
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sci
      PGDATA: /var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
