version: '3.1'
services:
  jupyter:
    build: './jupyter'
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
  mongo:
    image: mongo:5.0.5
    hostname: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
  postgres:
    image: postgres:14.1
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sci
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://username:password@mongo:27017/'
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: appademin
      ME_CONFIG_BASICAUTH_PASSWORD: kaffesmakpådongeln
