apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 'appademin/sci-api:1.11.1'
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              name: web
              protocol: TCP
          env:
          - name: NODE_ENV
            value: production
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: postgres-host
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: postgres-dbname
          - name: PYTHON_API
            value: http://python-counts-service:8080
          - name: REDIS_URL
            value: redis://redis-service:6379
          - name: APN_TOPIC
            value: com.appademin.sci-movement
          - name: GCM_KEY
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: gcm-key
            value: AAAAj3CFwnk:APA91bFy6bfEBPkRnrFf645tuCyXra1h8xFyNzQmXXvQKbEu-vqbXDaS_iWXFSLj8-AiioAgoBcTeYYyQWl0O4sS12CbKkJeZu1GzOp81ocTBTHvAZanmEcobdm2HY_1go8R27Upthhw
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 4000