apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        type: worker
      containers:
        - name: api
          image: 'appademin/sci-api'
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              name: web
              protocol: TCP
          env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: postgres-host
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: postgres-dbname
          - name: PYTHON_API
            value: http://python-counts-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 4000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sci-api-ingress
spec:
  routes:
  - match: Host(`sci-api.appadem.in`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: api-service
      port: 4000